version: '3'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: azerty
      WORDPRESS_DB_NAME: azerty
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example_password
     
